_target_: src.taskmodules.CorefHoiPreprocessedTaskModule

tokenizer_name_or_path: ???
genres: ["bc", "bn", "mz", "nw", "pt", "tc", "wb"]
max_num_speakers: 20
max_segment_len: 256
max_training_sentences: 5
