_target_: src.utils.execute_pipeline
input:
  _target_: pytorch_ie.DatasetDict.load_dataset
  path: pie/conll2012_ontonotesv5
  name: english_v12
  #base_dataset_kwargs:
  data_dir: ${oc.env:CONLL2012_ONTONOTESV5_DATA_DIR}
