defaults:
  - tacred_base
  - _select_n
  - _convert_documents
  - _collect_statistics

convert_documents:
  function: src.document.conversion.token_based_document_with_entities_and_relations_to_text_based
  result_type: src.document.types.TextDocumentWithLabeledEntitiesAndRelations

collect_statistics:
  _enabled_: false
  labeled_field: relations
  text_field: text
